project:
  type: website

website:
  title: "Zak Varty"
  site-url: "https://www.zakvarty.com"
  favicon: "assets/00_favicon/favicon.ico"
  twitter-card: true
#    creator: "@zakvarty"
  cookie-consent:
    type: express
    style: simple
    palette: light
  #prefs-text: "This site uses Google Analytics to analyse website traffic and improve your expreience of the site."
  google-analytics:
    tracking-id: "G-29RLTHLZB5"
    anonymize-ip: true

  navbar:
    background: primary
    search: true
    #left:
    #  - href: index.qmd
    #    text: Home
    #  - about.qmd
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd
      - text: Professional
        menu:
          - professional/research.qmd
          - professional/teaching.qmd
          - professional/talks.qmd
          - professional/bookmarks.qmd
      - text: Personal
        menu:
          - personal/reading-record.qmd
      - icon: twitter
        href: "https://www.twitter.com/zakvarty"
      - icon: github
        href: "https://github.com/zakvarty"
  page-footer:
    #background: light
    border: true
    left: "Copyright 2022, Zak Varty."
    center: ""
    right:
      - icon: twitter
        href: "https://www.twitter.com/zakvarty"
      - icon: github
        href: "https://github.com/zakvarty"
      - icon: google
        href: "https://scholar.google.com/citations?user=3H4vg4cAAAAJ&hl=en&oi=ao"

format:
  html:
    theme: [litera, custom.scss] #litera
    #css: styles.css
    toc: true



