---
format:
  html:
    toc: false
---
# Bookmarks 

A collection of helpful resources that I might want to find again in the future or point other people towards.

### Advice: Faculty 

- [Thread](https://twitter.com/sarahlsheffield/status/1553811480264560641) by Sarah Sheffield (@sarahsheffield) advice for new faculty. 
- [Course](https://drive.google.com/file/d/1j4ckk6TVKScNQSZTQOY5hI1HEiJLRS_k/view) Free 10 week course on google drive about writing academic an academic syllabus. Course by @DLabree, recommended by Elena Aydarova (@aydarova).
- [Tweet](https://twitter.com/GeroGrams/status/1526924778170359808) by Gero Grams (@GeroGrams) on how to say no to things
- [Thread]() by Mine Dogucu (@MineDogucu) on learning/teaching (with) R. See also:
	- [Compilation of free R resources](learnR4free.com) 
	- [Bayesian inference book](bayesrulesbook.com) 
	- [Teaching webpage](mdogucu.ics.uci.edu/teaching.html) 
	- [Blog on data pedagogy](datapedagogy.com)
- [Thread](https://twitter.com/wes_kao/status/1533463689097056256) by Wes Kao (@wes_kao) on managing up
- [Thread](https://twitter.com/VnVrinda/status/1517652396041818115?s=20&t=cXDVFRK_1_IKKHHyiRKLVw) by Vrinda Nair (@VnVrinda) on 22 tools for your PhD Journey
- Managing research careers tool by Edinburgh University [Thread](https://twitter.com/BoswellPol/status/1556904096644431872?s=20&t=cXDVFRK_1_IKKHHyiRKLVw) and [Webpage](https://www.ed.ac.uk/researchers/career-development/research-careers-tool)
- [Talk](https://www.youtube.com/watch?v=Jmdz0p_gTww) by Laura Albert (@lauraalbertphd) on time management: Do less, Do it faster, Do it at the right time. 


### Advice: Graduate Students 

- [Thread](https://twitter.com/MTJBetts/status/1548251832903823365) by Matt Betts on 8 questions to consider before starting a PhD.
- [Thread](https://twitter.com/MCDuncanLab/status/1553399486831104002) by Maram Duncan (@MCDuncanLab) on the hidden curriculum for new grad students 
- [Thread](https://twitter.com/LifeAfterMyPhD/status/1536051032261660674) by @LifeAfterMyPhD on 5 low-stakes steps to set yourself up for an industry job search
- [Thread](https://twitter.com/mathladyhazel/status/1518059799602253824?s=20&t=cXDVFRK_1_IKKHHyiRKLVw) by @mathladyhazel on the best math books for self-learners
- [Thread](https://twitter.com/alexeble/status/1019278324680593408?s=20&t=cXDVFRK_1_IKKHHyiRKLVw) by Alex Eble (@alexeble) on adivce for thriving in a PhD. Full document [here](http://alexeble.com/s/PhDGuidebook.pdf). Note: has US and economics focus, but translates well.
- [Website](https://www-users.york.ac.uk/~mb55/pubs/pbstnote.htm) Stats Notes in the British Medical Journal. Like a dictionary but for stats words and methods.
- [Book](https://www.oreilly.com/library/view/essential-math-for/9781098102920/) Esstential Math for Data Scienceby Thomas Nield. Recommended by Vicki Boykis for those tooking for an intro/refresher on linear algebra, probability and statistics.


### Agent based modelling 

- [Paper](https://inet.ox.ac.uk/files/JEL-v2.0.pdf) review of agent based model (preprint of JEL - chunky at 90 pages!) 


### Analysis and Asymptotics 

- [Video Lectures](https://www.youtube.com/watch?v=KZsk8B_z8pI&list=PL5EH0ZJ7V0jV7kMYvPcZ7F9oaf_YAlfbI) by Steven Strogatz (@stevenstrogatz) on asymptotics and pertubation methods.


### Causal Inference 

- [Lecture Notes](https://mattblackwell.github.io/gov2003-f21-site/materials.html) by Matt Blackwell, "Causal Inference with Applications"
- [Paper](https://journals.sagepub.com/doi/full/10.1177/1745691620921521) The taboo against explicit causal inference in nonexperimental psychology. Suggested by Brian Nosel (@BrianNosek)
- [Thread](https://twitter.com/volokuleshov/status/1549180199006310401) by Volodymyr Kuleshov (@volokuleshov) about the ICML 2022 tutorial on Causality and Fairness
- [Video](https://youtu.be/KNPYUVmY3NM) Science before statistics: Causal Inference by Richard McElreath (3 hour crash course in causal inference)
- [Video Series](https://www.youtube.com/playlist?list=PLDcUM9US4XdMROZ57-OIRtIK0aOynbgZN) Statistical Rethinking (2022) by Richard McElreath on Youtube 


### Coding (General) 

#### Short-form 

- [Article](https://tekin.co.uk/2020/03/maintain-a-global-git-ignore-file) on setting up a private .gitignore to keep a clean codebase
- [Book](https://py-pkgs.org/) / website on package development in Python. (Think Hadley & Bryan's R packages but for Python) Recommended by @EmilyRiederer 
- [Book](https://themissingreadme.com/) The missing readme by Chris Riccomini and Dmitriy Ryaboy
- [Paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007142) Ten Simple Rules for Taking Advantage of Git and GitHub
- [Sildes](https://aosmith16.github.io/spring-r-topics/slides/week07_more_git.html#1) by Ariel Muldoon (@aosmith16) on "More git and github - collaborators, merege conflicts and pull requests"
- [Docs](https://rstudio.github.io/renv/articles/renv.html) for `{renv}`

#### Long-form 

- [Intermediate programming course](https://iprogramming.bacpop.org/)
- [Missing Semester](https://missing.csail.mit.edu/) (MIT Computer Science)
- [Building reproducible analytical pipelines with R](https://raps-with-r.dev/) 
- [Statistical Programming Paradigms and Workflows](https://www.stephaniehicks.com/jhustatprogramming2023/)


### Docker  

- [Thread](https://twitter.com/alexkgold/status/1545768835671891971) by Alex Gold (@alexkgold) on getting started with Docker. Free online [book](https://do4ds.com/chapters/sec1/docker.html)

### Databases 

- [Article](https://architecturenotes.co/things-you-should-know-about-databases/) by architecture notes (@arcnotes) on "Things you should know about databases"

### Datasets 

- [Thread](https://twitter.com/WeAreRLadies/status/1550116612413394944) by R Ladies - Sources of Messy(ish) data

### Data Ethics 

- The Verge - [AI Drug development maske chemical weapons](https://www.theverge.com/2022/3/17/22983197/ai-new-possible-chemical-weapons-generative-models-vx) 
- Nature - [AI Drug development maske chemical weapons](https://www.nature.com/articles/s42256-022-00465-9)

- Richard McElreath recommendation of [paper](https:// statistics.fas.harvard.edu/files/statisti cs-2/files/statistical_paradises_and_paradoxes.pdf) by Xiao-Li Meng on how data quality influences effective sample size

- [Thread](https://twitter.com/svpino/status/1546826721839566848) by Santiago (@svpino) on imbalanced datasets
- [Tweet](https://twitter.com/AdamKruchten/status/1526916448668438528) by Adam Kruchten (@AdamKruchten) on when we care about marginal or conditional effects.
- [ASA article](https:// amstat.org/asa/files/pdfs /YCR-2020WorkandSalarySurvey.pdf) on the 2020 work and salary survey, showing women tend to earn less in base salary and total income but that in a regression gender is not significant predictor of total income.
- [NPR story](https://www.npr.org/2019/03/05/700288695/google-pay-study-finds-its-underpaying-men-for-some-jobs?t=1660076296012) Where Google find that men are underpaid
- [Thread](https://twitter.com/PHuenermund/status/1540262891890278402) by Paul Hunermund (@PHunermund) on the above google article.
- [Preprint](https://arxiv.org/abs/2206.07758) on reconstructing large portions of training data from a trained neural network 
- [Paper](https://dl.acm.org/doi/abs/10.1145/3476058) Do Datasets Have Politics? Disciplinary Values in Computer Vision Dataset Development. Suggested by Abeba Birhane (@Abebab)
- [Paper](https://www.nature.com/articles/s41586-021-04198-4) Big data loses to good data. Unrepresentative big surveys significantly overestimated US vaccine uptake.
- [Paper](https://arxiv.org/abs/2110.09167) On extending LinearSHAP, TreeSHAP and DeepSHAP to RKHS-SHAP. Found through tweet by Siu Lun Chau (@Chau9991).
- **Chapter 33** on interpretability of book [Probabilistic Machine Learning: Advacned Topics](https://probml.github.io/pml-book/book2.html)by Kevin Murphy (@sirbayes), Been Kim (@\_beenkim) and others.
- [Book](https://clairemckaybowen.com/book/) by Claire McKay Bowen "Protecting your privacy in a data-driven world"
- [Tweet](https://twitter.com/rashabun/status/1517158099546607616?s=20&t=cXDVFRK_1_IKKHHyiRKLVw) by Rasha Shrain (@rashaben) requesting reading materials on p-values and p-hacking
- [Course](https://rohanalexander.com/reading_course-ethics.html) 12 week reading course on Ehics and Data Science by Rohan Alexander


### Data Visualisation 

- [Thread](https://twitter.com/patilindrajeets/status/1541790477472735232) by Indrajeet Patil (@patilindrajeets) on the effective use of colours in data vis. 
- [R Package](https://easystats.github.io/performance/) `{performance}` for aesthetically pleasing ggplot sytle diagnostic plots. (The qq plot even has tolerance intervals!)
- [Blog Post](https://themockup.blog/posts/2020-12-26-creating-and-using-custom-ggplot2-themes/) by Thomas Mock on Creating and using custom ggplot2 themes
- Blog Posts by Ameila McNamara (@AmeliaMN) about [Histograms](http://tinlizzie.org/histograms/) and [Kernel Density Estimation](https://mathisonian.github.io/kde/)

### History of Statistics 

- [Course](https://rohanalexander.com/history_of_the_data_sciences.html) 10-week reading list on "History of Statistics and Data Sciences" by Rohan Alexander

### Markdown 

- [Tweet](https://twitter.com/realstevebauman/status/1537879545272971266) by Steve Bauman (@realstevebauman) pointing out that Github's markdown now supports note and warning blockquotes
- [Tweet](https://twitter.com/zevross/status/1519318012846817282) by Zev Ross on using the character ├ to get aesthetically pleasing subsections in RStudio
- [Tutorial](https://help.mentimeter.com/en/articles/410896-embed-your-presentation-on-a-webpage) on embedding mentimeter into webpages (try with html slides???)

### Memes 

- [Status code 400 meme](https://twitter.com/da_667/status/1546556347671580672) by @da_667
- [The binary search tree actually exists](https://twitter.com/MrAhmadAwais/status/1526722046037741572) by Ahmad Awais (@MrAhmadAwais)
- [Data Science Dinosaur](https://tekin.co.uk/2020/03/maintain-a-global-git-ignore-file) A computer science python eating a statistics elephant 


### Science Communication 

- [Thread](https://twitter.com/CT_Bergstrom/status/1544398162135109632) by Carl Bergstrom (@CT_Bergstrom) and Ryan McGee (@RS_McGee) telling the story of a paper using a comic strip and stick-figure Darwin.
- [Thread](https://twitter.com/TessaRDavis/status/1532424356239900672?s=20&t=cXDVFRK_1_IKKHHyiRKLVw) by Tessa Davis on slide design to keep your audience engaged
- [Thread](https://twitter.com/DorsaAmir/status/1514990088962265090?s=20&t=cXDVFRK_1_IKKHHyiRKLVw) by Dorsa Amir (@DorsaAmir) on slide design
- [Website](https://www.openpeeps.com/) OpenPeeps - Open Source hand drawn individual characters
- [Blog Post](https://www.katiejolly.io/blog/2021-03-16/designing-slides) by Kate Jolly (@katejolly6) on designing slides in xaringan with `xaringanthemer` and css.

### Machine Learning 

- [Blog Post](https://lernapparat.de/statistics-deep-learning-nonparametric) on double descent in neural network performance
### Optimisation
- [Video](https://www.youtube.com/watch?v=8mjcnxGMwFo) by Trefor Bazett (@TreforBazett) on using Lagrange multipliers to solve constrained optimisation problems
- [Video Series](https://www.khanacademy.org/math/multivariable-calculus/applications-of-multivariable-derivatives/lagrange-multipliers-and-constrained-optimization/v/constrained-optimization-introduction) by @3blue1brown on constrained optimisation (hosted on khan academy)
- [Course Notes](https://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/) Advanced Data Analysis from an Elementary Point of View

### Parquet 

- [Thread](https://twitter.com/paulabartabajo_/status/1550133535310090240) by Pau Labarta Bajo (@paulabartabajo_)

### Point processes 

- [Course Material](http://www.stat.ucla.edu/~frederic/222/S21/) By Rick Schoenberg on point process models
- [Blog Post](https://benjamincretois.netlify.app/post/fitting-point-process-models-in-stan-part-2/) by Benjamin Cretois on fitting point process models in `stan`.

### Professional Development 

- [Tweet](https://twitter.com/francisco_yira/status/1544004372182421505) by Francisco Yirá (@francisco_yira) about designing a personal learning plan.

### Quarto 

- [Samatha Csik - Creating Quarto Websites](https://ucsb-meds.github.io/creating-quarto-websites/)


### SQL 

- [Thread](https://twitter.com/tcarpenter216/status/1527085560740782082) by Tom Carpenter (@tcarpenter216) on translating dplyr skills to SQL

- Online resources for learning SQL, as recommended by Ijeoma Okereafor (@MeetIjeoma)
	- http://sqlbolt.com
	- http://w3schools.com/sql
	- http://mode.com/sql-tutorial
	- http://sqlteaching.com
	- http://SQLZoo.net
	- http://selectstarsql.com  
	- https://pgexercises.com

- SQL games recommended by Vikas Rajputin (@vikasrajputin)
	- (SQL Island)[https://sql-island.informatik.uni-kl.de/] (In German but chrome translation is pretty good) 
	- (SQL Murder Mystery)[https://mystery.knightlab.com/]
	- (SQL Polic Department)[https://sqlpd.com/]


### Workflow 

- Jenny Bryan - Naming Things [(Slides)](https://speakerdeck.com/jennybc/how-to-name-files)
- [Talk](https://www.youtube.com/watch?v=th79W4rv67g) by David Robinson on "The unreasonable effectiveness of public work"

### Writing 

- [Books](https://www.helensword.com/books-on-writing) on writing suggested by Helen Sword, author of Stylish Academic Writing.
