---
title: "Recipies"
search: false
---

<!-- TEMPLATE
## Recipe title
_recipe source_ 

__Prep:__ mins    __Cook:__ mins     __Serves:__  

__Ingredients:__
 *
 *
 *
__Method:__ 
1.
2.
3.

--->

## Mains

### Goat's Cheese Ratatouille 
_BBC Good food Sept 2018_ 

__Prep:__ 45mins    __Cook:__ 45mins     __Serves:__ 6 

__Ingredients:__

 * 4 tbsp olive oil
 * 2 red onions, chopped
 * 2 garlic cloves, finely chopped
 * 2 aubergines, diced
 * 2 red peppers, diced 
 * 1 tsp smoked paprika 
 * 2 tbsp balsamic vinegar 
 * 1 tsp soy sauce (optional)
 * 500ml passata 
 * 200g goat's cheese
 * 4 courgettes cut into thin rounds (4? Yes, really. Mix of green & yellow best) 
 
 _For the cheese sauce_:
 
 * 400ml milk 
 * 50g unsalted butter 
 * 50g plain flour 
 * 80g parmesan, grated 
 
__Method__: 

 1. Heat 1tbsp oil and gently cook onions & garilc 5 mins until browning. Add aubergine & peppers, cook further 4 mins adding oil as needed. Season well and add the paprika, soy and vinegar. Add pasata and simmer 5 mins to thicken. Turn off heat. (Can do this step up to 2 days ahead of time & fridge it)
 2. For cheese sauce: heat milk gently to simmer. Melt butter in sparate pan, add flour and slowly add hot milk while whisking. Simmer 2-3 mins stirring continually until thinckened slightly. Add parmesan and seasoning. 
 3. Tip ratatouille into ovenproof dish and cover with cheese sauce. Crumble the goat's cheese on top and arrange courgette slices over the cheese. (Can be done several hours ahead) 
 4. Heat oven to 220C/200C fan/gas 7. Brush courgettes with remaining oil and season with salt. Bake 25-30 mins until courgettes cooked and starting to brown. Remove and rest 15 mins before serving with crusty bread. 
 
### Sweet potato & Lentil Curry
_BBC GoodFood Sept 2018_ 

__Prep:__ 10mins    __Cook:__ 30mins     __Serves:__ 4 

__Ingredients:__
 * 2 tbsp rapeseed oil 
 * 1 onion, chopped 
 * 1 tsp ground cumin 
 * 1 tbsp Madras / medium curry powder 
 * 200g red lentils
 * 2 sweet potatoes, peeled and cubed
 * 750ml - 1L vegetable stock 
 * 400g tinned tomatoes
 * 200g green beans (optional)
 * 4 tbsp natural yoghurt 
 * 1/2 small bunch corriander (optional)
 * 1/4 cucumber, chopped (optional) 
 * naan bread & rice to serve 
 
__Method:__ 

 1) Heat oil in large pan and fry onion until softened. Add spices and fry 1 min. Add lentils, stock, sweet potato and tomatoes.
 2) Bring to boil and reduce to simmer and cover for 20-30 mins until sweet potato is tender. Add green beans and simmer 2 mins. Stir in yoghurt and seasoning as required. 
 3) Serve with rice & naan, garnishing with cucumber and corriander if desired. 


### Sticky Orange Stir-Fry
_BBC GoodFood Sept 2018_ 

__Prep:__ 25mins    __Cook:__ 10mins     __Serves:__ 4

__Ingredients:__
 * 2 cloves garlic, finely grated
 * Thumb of ginger, finely grated
 * 1 red chilli, thinly sliced
 * 1 tsp five-spice
 * 1 tsp sesame oil 
 * 6 skinless chicken thigh fillets, diced into small pieces
 * 1-2 tbsp sunflower oil
 * 1 red onion, thinly sliced 
 * 100g mange tout or snap peas
 * 100g tenderstem broccoli 
 * 2 carrots, julienned 
 * 100g salted peanuts to garnish (optional)
 
 _For the sauce_
 * 1/2 orange, juiced
 * 3 tbsp honey
 * 1 tsp soft dark brown sugar
 * 2 tbsp dark soy sauce 
 * 1 tbsp Chinese rice wine (Shaosing)

__Method:__ 

1. Whisk together the garlic, chilli, five-spice and sesame oil in a bowl. Add the chicke pieces and mix well until coated.
2. Whisk together the sauce ingerdients in a small bowl.
3. In a large wok heat the sunflower oil to smoking point. Fry the chicken until golden brown and cooked through. 
4. Add vegetables, and a little oil if required, and stir-fry until tender.Add sauce and simmer for further 3-4mins until reduced. 
5. Add peanuts and serve.  


### Cod with sundried tomatoes and pancetta 
_BBC GoodFood Sept 2018_ 

__Prep:__ 5 mins    __Cook:__ 20 mins     __Serves:__ 4 

__Ingredients:__
 * 100g sundried tomatoes, drained. 
 * 400g canned chopped tomatoes
 * 4 skinless cod fillets
 * 4 slices thin pancetta
 
__Method:__ 

 1. Mix the sundried and canned tomatoes and season. Tip the sauce into an ovenproof dish and add the fish. Top each fillet with a tsp of oil from the sundried tomatoes.  Bake at 200C/180C fan for 15-20 mins.
 2. Heat a medium frying pan and cook the pancetta on both sides for 1 min or until crisp. Top the fish with pancetta shards and serve. 


### Tomato & Mozzarella Orzo Bake 
_BBC GoodFood Sept 2018_ 

__Prep:__ 10 mins    __Cook:__ 35 mins     __Serves:__ 2 

__Ingredients:__
 * 150g orzo
 * 1/2 tbsp olive oil 
 * 2 roasted red peppers from jar, roughly chopped
 * handful sundried tomatoes
 * big pinch chilli flakes 
 * 1/2 tsp dried oregano 
 * 400g tin chopped tomatoes
 * 2-3 cloves garlic, finely chopped
 * 125g mozzarella
 
__Method:__ 

 1. Heat oven 200C/180C fan. In a casserole dish, mix the orzo, oil, red peppers, sundried tomatoes, chilli flakes and oregano. Add the tomatoes, and half a tin of water, stirring well.
 2. Cover and bake for 20 minutes until the pasta is almost cooked. 
 3. Remove from oven and stir. Top with the mozzarella and return to the oven for a further 10 minutes. 
 4. Remove from oven and leave to stand for 5 minutes before serving.  

### Roasted Aubergine with Peanut Dressing
_BBC GoodFood Sept 2018_ 

__Prep:__ 10 mins    __Cook:__ 30 mins     __Serves:__ 2 

__Ingredients:__
 * 1 tbsp oil 
 * 1 tbsp sweet chilli sauce 
 * 2 tsp soy sauce
 * 1 aubergine
 * 1 tbsp peanut butter
 * 1/2 lime 
 * sprig corriander, finely chopped
 * 2 spring onions, finely chopped
 * rice to serve
 
__Method:__ 

 1. Heat oven to 180C/ 160 fan. Mix the oil with half of each of the sweet chilli and sauces. Cut the aubergine lengthways into wedges and place on a lined baking tray. Pour over the mixture and coat the wedges. Bake for 30 mins.
 2. Mix the remaining soy, sweet chilli and peanut butter. Add the juice from the lime and a splash of water and mix well. 
 3. Cook the rice and stir through the corriander and spring onions. 
 4. Remove the aubergine from the oven and serve on the rice, topping the dish with the peanut sauce.
  
### Sausage and Kale Gnocchi
_BBC GoodFood Oct 2018_ 

__Prep:__ 5 mins    __Cook:__ 15mins     __Serves:__ 4  

__Ingredients:__
 * 1 tbsp olive oil
 * 6 pork sausages / eqiv. sausage meat
 * 1 tsp chilli flakes
 * 1 tsp mustard seeds 
 * 500g fresh gnocchi 
 * 500ml chicken stock 
 * 100g chopped kale 
 * 40g parmesan, finely grated 
 
__Method:__ 

 1. Heat oil in a large, high sided frying pan. Cut the sausage meat into 1cm cubes and fry over medium heat until crisp around the edges. Add the chilli flakes and mustard seeds. Remove from pan with slotted spoon.
 2. Tip gnocchi into pan, fry for 1 min then add the stock. Once bubbling, cover and simmer for 3 mins then stir in the kale. Cook 2 mins further until gnocchi tender and kale wilted. 
 3. Stir ine parmesan and top with the sausage meat. Serve with crusty bread. 

## Desserts 

### Orchard Fruit Tatin with Cinnamon Cream
_BBC GoodFood Sept 2018_ 

__Prep:__ 30 mins plus chilling   __Cook:__ 1 hour     __Serves:__ 6-8  

__Ingredients:__
 * 200g golden caster sugar
 * 100ml cider (optional)
 * 1 cinamon stick 
 * 50g cold butter, sliced
 * 3 Granny Smith apples, peeled cored and quartered
 * 3 firm pears, preeled, cored and halved 
 * 340g sheet all-butter puff pastry
_For the cream:_ 
 * 1 tsp ground cinnamon 
 * 100g creme fraiche 
 * 150ml double cream
 * 70g icing sugar 
 
__Method:__ 

 1. Add sugar, cider and cinnamon stick to medium (24cm) saucepan and bring to boil. Reduce until caramelised and amber, remove from heat and add butter to make a sticky sauce. While still warm, pack the pan with apples and pears. 
 2. Roll pastry and drape over fruit and use a spoon to tuck edgesof pastry in. Fridge for 1 hour or overrnight. 
 3. Whisk togther the cinnamon creme ingredients to form soft peaks. Chill in fidge. 
 4. Heat oven 200C/180C fan Prick a few holes in top of pastry. Put pan in oven and bake 45 mins and rest 10 mins. Turn out tart onto a dinner plate and serve sliced with the cinnamon cream.  
 
### Peach Melba Pie
_BBC GoodFood Oct 2018_ 

__Prep:__ 30mins    __Cook:__ 1hr plus chilling & cooling    __Serves:__ 6-8 

__Ingredients:__
_For the pastry_
 * 175g self-raising flour, plus more for dusting
 * 175g white spelt flour
 * 160g unsalted butter, chilled and cubed
 
_For the filling_
 * 4 ripe peaches 
 * 1/2 lemon, juice only
 * 1 tbsp cornflour
 * 1 tsp vanilla extract 
 * 3 tbsp light muscovado sugar 
 * 1 tbsp runny blossom honey
 * 200g raspberries
 * 10g chilled butter
 * 1 egg, beaten 
 * 2 tbsp demerara sugar
 * vanilla icecream or whipped cream to serve
 
__Method:__ 

 1. Combine flours, butter and pinch of salt in food processor and blitz to a fine crumb. Add cold water 1 tbsp at a time (4-5 tbsp) pulsing unitl the mix begins to cling together. Tip out and knead to a pliable dough. Split in half, flatten each portion. Wrap in cling film and refrigerate for at least 1 hour.
 2. Roll out pastry disks and refrigerate for further 10 minutes. Heat the oven to 180C/ 160 fan.
 3. Stone and quarter the peaches, cut each in two and toss in a bowl with the lemon juice, cornflour, vanilla extract, sugar, honey and raspberries. Add the butter in small pieces. 
 4. Line a 24cm pie dish with pastry and prick all over and fill with peach mixture. Cover pie with second pastry sheet and crimp, cutting three 8 cm slits in the lid. 
 5. Brush with egg wash and sprinkle with demerara sugar. Bake 55 mins - 1 hour until deeply golden and bubbling. Cool 10 mins and serve with cream or icecream.

## Spice Mixes 

### Morocan Spice Mix
_BBC GoodFood Oct 2018_ 

__Prep:__ 5 mins    __Cook:__ NA    __Serves:__ NA 

__Ingredients:__
 * 2 tbsp coriander seeds 
 * 1 tbsp cumin seeds 
 * 1 1/2 tsp fennel seeds
 * 1/2 tsp black pepper
 * 1/4 tsp ground ginger 
 * 1 tsp ground cinnamon 
 * good pinch saffron 
 
### Caribbean Spice Mix
_BBC GoodFood Oct 2018_ (add to meat or corn)

__Prep:__ 5 mins    __Cook:__ NA    __Serves:__ NA 

__Ingredients:__
 * 2 tsp ground cinnamon 
 * 1 tbsp black peppercorns
 * 1 tbsp dried thyme 
 * 1 tsp dried ground ginger 
 * 2 dried bay leaves 
 * 8 allspice berries
 * 1 1/2 tsp cayenne pepper 
 * 1/2 nutmeg grated

### Smoky Mexican Spice Mix
_BBC GoodFood Oct 2018_ (add to wedges or chicken)

__Prep:__ 5 mins    __Cook:__ NA    __Serves:__ NA 

__Ingredients:__
 * 1 tbsp cumin seeds 
 * 2 tsp smoked paprika 
 * 1 1/2 tsp ground oregano 
 * 4 ground cloves
 * 2 tbsp smoked salt flakes
 * 2 tbsp chipotle chilli flakes 
 
## Drinks 

### The Bramble
_BBC GoodFood Oct 2018_ 

__Prep:__ 5 mins    __Cook:__ NA    __Serves:__ 1 

__Ingredients:__
 * 50ml gin
 * 25ml lemon juice
 * 3/4 tbsp sugar syrup 
 * ice cubes
 * crushed ice
 * 3/4 tbsp creme de mure
 * 1 lemon slice and a blackberry to serve
 
__Method__

 1. Shake the gin, lemon juice and syrup in a cocktail shaker with ice. Strain into a glass ofcrushed ice and drizzle over th creme de mure so that it 'bleeds' into the drink. Garnish and serve.
