---
format:
  html:
    toc: false
---
# Research 

## Research Interests 

My research interests lie in the intersection between applied and methodological statistics. My past projects have focused on missing data, predictive analytics, extreme value analysis and point process modelling.

I'm particularly interested in developing efficient inference methods for non-standard data generating mechanisms to better model the rich, complex data sets that arise from environmental and industrial processes.

I also have a developing interest in education research. At the moment I am most interested in teaching and learning for postgraduate students and, more broadly, statistics education at all levels. 

## Projects 

> __Spatio‐Temporal Modelling of Extreme Induced Seismicity in the Presence of An Evolving Measurement Network.__
> ([article](https://onlinelibrary.wiley.com/doi/pdf/10.1002/env.70090))
>
> Work with [Conor Murphy](https://www.linkedin.com/in/conor-murphy-a0a050158/) developing a novel extreme-value modelling procedure that uses known changes in the earthquake measurement network to automatically select a parametric, spatio-temporal threshold that accounts for undetected earthquakes. We also introduce methods to propagate uncertainty in the extreme-value model, threshold parameters and threshold formulation through to future hazard estimates. 


>__Integrating Experts’ Belief in Upper Tail Inference for Modelling of Human-Induced Earthquake Magnitudes.__ 
> ([article](http://dx.doi.org/10.1007/s13253-025-00710-9)) 
>
> Work with [Wanchen Yue](https://www.lancaster.ac.uk/stor-i/about-us/people/wanchen-yue) on how to incorporate expert opinion on upper bounds for earthquake magnitudes (not just the endpoint itself) into both frequentist and Bayesian tail inference.
>Applied to the Groningen gas field (NL), this approach improves estimates of extreme magnitudes and strengthens seismic hazard assessment & risk management. 


> __Automated threshold selection and associated inference uncertainty for univariate extremes.__
> ([article](https://www.tandfonline.com/doi/full/10.1080/00401706.2024.2421744)) 
>
> Work with [Conor Murphy](https://www.lancaster.ac.uk/maths/people/conor-murphy2), developing a novel methodology for automated threshold selection in univariate extreme value modelling and to propagate uncertainty in this threshold choice through to estimates of extreme quantiles. The effectiveness of our method is demonstrated though an extensive simulation study, compared to the leading existing methods and applied to the well-known and troublesome example of the River Nidd dataset. 

> __Inference for extreme earthquake magnitudes accounting for a time-varying measurement process.__
> ([arXiv](https://arxiv.org/abs/2102.00884))
>
> Motivated by earthquake catalogues, we consider variable data quality in the form of rounded and incompletely observed data. We develop an approach to select a time-varying modelling threshold that makes best use of the available data in an extreme value analysis, accounting for uncertainty in the magnitude model and for the rounding of observations. 

> __Statistical Modelling of Induced Earthquakes__ 
> ([PhD Thesis](https://doi.org/10.17635/lancaster/thesis/1436)).
>
> My PhD thesis focused on how to model anthropogenic earthquakes while making best use of the limited available data. Firstly, a selection of physically-motivated parametric models are explored for describing the link between gas extraction and induced earthquake locations. Secondly, new inference methods are developed that allow improvements to the earthquake detection network to be included when modelling extreme earthquake magnitudes. Finally, a reparameterised and extended version of the Epidemic Type Aftershock model introduced. This both allows for more efficient inference and relaxes the common assumption of independent and identically distributed magnitudes.

> __A review of simulated annealing techniques:__ Simulated annealing is a metahuristic technique mainly used for combinatorial optimisation. Applications, parallelisation and extensions of the technique were reviewed.

> __Inference on censored networks:__ Networks are censored when existing nodes or edges are not observed. Methods for inference under different types of missingness were explored. Master's project supervised by Dr. Christopher Nemeth.

> __Computationally intensive methods for modelling household epidemics:__
Approximate Bayesian Computation was utilised to allow inference on disease models with intractable likelihoods. Master's dissertation supervised by Prof. Peter Neal.


## Conference and workshop contributions

| Date      | Event | Location |
|-----------|:-----------------|------------------:|
| Sep 2025  | Royal Statistical Society conference | Edinburgh, UK. |
| Sep 2024  | Royal Statistical Society conference | Brighton, UK. |
| Jun 2024  | UK Conference on Teaching Statistics | Manchester, UK. |
| Nov 2023  | RSS Local Group Meeting | Bath, UK. |
| Sep 2023  | Royal Statistical Society conference | Harrogate, UK. |
| Sep 2023  | RSS pre-conference workshop | Harrogate, UK. |
| Jun 2023  | IMA Idea Exchange: Mathematicians and Statisticians Teaching in Higher Education | Remote. |
| Sep 2022  | Royal Statistical Society conference | Aberdeen, UK. |
| Jun 2022  | M\_max workshop | Amsterdam, NL. |
| Jan 2021  | CRG Extremes workshop | Remote. |
| May 2020 | STOR-i time-series and spatial statistics workshop | Remote. | 
| Sept 2019 | Interfaces in extreme value theory workshop| Lancaster, UK. |
| Sept 2019 | Royal Statistical Society conference | Belfast, UK. |
| Aug  2019 | International statistical seismology workshop (StatSei11) | Hakone, JPN.|
| Jul 2019 | GRASPA (Italian Environmetics Society)| Pescara, IT. |
| Jan 2019 | STOR-i annual conference | Lancaster, UK. |
| Jan 2018 | STOR-i annual conference | Lancaster, UK. |


## Research Project Supervision

I have had the good fortune to supervise some exceptional early career researchers in their postgraduate and undergraduate research projects. Below is a list of the students I have supervised along with their project titles.

### PhD 

- __Wanchen Yue__ (Oct 2023 - Present) - Statistical earthquake models to account for measurement errors and dependence.

- __Conor Murphy__ (Oct 2021 - Aug 2025) - Assessment of hazard and risk due to induced seismicity for underground CO2 Storage and oil and gas production assets. 

### MSc and MSci

#### Academic Year 2024-25

<!-- AY 2025-26 -->

- __Nayu Ding__ - A comparative study of earthquake forecasting methods in California.
- __Seojeong Hong__ - Parameter bias in ETAS models under short-term incompleteness.
- __Xin Lin__ - A time-varying ETAS model for induced seismicity decay in Oklahoma.
- __Ti Qing__ - Benchmarks for medium-term magnitude predictions in the Sichuan region using LSTM networks and random forests.
- __Sachit Ramakrishnan__ - Physics-informed Bayesian ETAS: a study of the 2019 Ridgecrest earthquake.
- __Nattanicha Reanroo__ - Estimating economic time-to-recovery for Japanese earthquakes.
- __Zhaolan Wang__ - Investigating the impact of declustering on short-term earthquake forecasting.

- __Kaihua Su__ - Identifying fore-, main-, and aftershock Clusters (title TBC).
- __Zhicheng Zhang__ - Dependence of magnitudes within fore-/main-/aftershock clusters (title TBC).

<!-- AY 2024-25 -->

- __Leyli Cowell__ - Structural causal models for tail dependencies among European currencies.
- __Katerina Kaplunova__ - Robust extreme-value anomaly
detection in non-stationary streams. 
- __Lauryne Moyse__ - Adaptive quantile boosted
classification for imbalanced data. 
- __Moad Ouaaline__ - Multivariate financial risk estimation via the SPAR model.
- __Arnav Agarwal__ - A compositional analysis of the UK energy supply
- __Yuqing Wang__ - Modelling extremal behaviour within the UK energy supply

#### Academic Year 2023-24

<!-- AY 2023-2024 -->
- __Brian Mac Carvill__ - Modelling extreme changes in
crude oil prices.
- __Yinglai Qi__ - Investigating the risk of developing diabetes using UK Biobank data.
- __Etienne Caprioli__ - Modelling extreme natural hazards in the United States of America. 
- __Ioannis Spanos__ - Peaks over threshold modelling with missing data.
- __Xinran Huang__ - Nonstationary ETAS models for temporal variations in
earthquake occurrences
- __Tommy Tong__ - Analysing the Dynamics and Catastrophic Events of Space Weather.
- __Zihan Yan__ - Analysis of significant wave heights in the North Atlantic Ocean. 
- __Jiahui Chen__ - Statistical modelling of earthquakes in the North Anatolian Fault Zone.
- __Jianjing Yu__ - Rare events in financial time series.


<!-- AY 2022-2023 -->
#### Academic Year 2022-23
- __Wanchen Yue__ - Statistical earthquake models to account for measurement errors and dependence.
- __Ash Bellett__ - Contextual bandits with non-stationary Gaussian process rewards.
- __Christian Liman__ - Multiple imputation for tree-based models.
- __Li Vern Teo__ - Catch me if you CNN: adversarial machine learning for detecting
synthetic content.
- __Minjian Wu__ - Outlier detection and adaptation under covariate shift.
- __Paula Cordero Encinar__ - Representing ignorance about extreme earthquake magnitudes.
- __Lucy He__ - Measurement errors in earthquake modelling.
- __Shantianfang Gao__ - Inhomogeneous Poisson point process estimation using spline methods.

<!-- AY 2021-2022 -->
#### Academic Year 2021-22
- __Diana Xu__ - An extreme value mixture model for natural gas prices.
- __Hugo Barnett__ - Hypothesis testing with the self-inhibiting Hawkes process.
- __Nan Zhou__ - Self-driving vehicles road safety analysis by application of extreme value theory.
- __Xuan Hou__ - An extreme value analysis of rainfall in London.
- __Conor Murphy__ - Assessment of hazard and risk due to induced seismicity for underground CO2 Storage and oil and gas production assets.


### Undergraduate

- __Natalie Young__ - Point pattern analysis in statistical ecology.
- __Peter Greenstreet__ - Self-exciting point process models.

