# Reading record 📚
This is where I record the books I read each year and the books I might like to read in the future. 

## Currently reading 📖
- Data Science Ethics - David Martens
- The Virgin Suicides - Jeffrey Eugenides

## TBR ⏲️
- How to do nothing - Jenny Odell
- Her Body and Other Parties - Carmen Maria Machado
- Something wicked this way comes - Ray Bradbury 
- The Hole -  Hye-Young Pyun, Sora Kim-Russell (Translator)
- Gender swapped fairytales - Karrie Fransman & Jonathan Plackett 
- Luster - Rven Leilani
- In the house in the dark of the woods - Laird Hunt
- Mexican Gothic - Silvia Moreno-Garcia

## TBR-ish ⏰❓
- Meanwhile in Dopamine City - DBC Pierre 
- Tyll - Daniel Kemlmann 
- How to win friends and influence people - Dale Carnegie 
- The Mr Porter guide to a better day 
- Professor Higgins's Problem Collection - Peter M Higgins 
- The discomfort of Evening - Marieke Lucas Rijneveld 
- Blood and guts in high school - Kathy Acker 
- The Nickel Boys - Colson Whitehead
- The Need - Helen Phillips
- The silence of the girls -  Pat Barker
- The ginger child - Patrick Flanery
- Bonjour Tristesse - Francois Sagan
- The Outsiders - S. E. Hinton
- Micro Avdentures - Alastair Humphreys
- Decline and Fall - Evelyn Waugh

## 2021 - 2022
1. The Secret History - Donna Tartt
2. Fahrenheit 451 - Ray Bradbury
3. Dune Messiah - Frank Herbert
4. On Earth We Are Briefly Gorgeous - Ocean Vuong 
5. Wow, no thank you - Samantha Irby 
6. Math without numbers - Milo Beckman 
7. The Penelopiad - Margaret Atwood 
8. Introduction to Statistical Learning
9. Boy Parts - Eliza Clark
10. How to take smart notes - Sonke Ahrens
11. If we were villians - M. L. Rio
12. The Windup Bird Chronicle, Book 1- Haruki Murakami
13. The Windup Bird Chronicle, Book 2 - Haruki Murakami
14. The Windup Bird Chronicle, Book 3 - Haruki Murakami
15. Treacle Walker - Alan Garner
16. Immune - Philipp Dettmer (DNF)
17. The Beauty of Everyday Things - Seotsu Yanagi 
18. Better Data Visualizations - Jonathan Schwabish 
19. Scientifically Speaking - Jo Filshie Browning
20. The Effect - Nick Huntington-Klein
21. ...

## 2020 - 2021
1. The authenticity project - Clare Pooley ♣️
2. Dune - Frank Herbert
3. How to make the world add up: Ten rules for thinking differently about numbers - Tim Harford
4. The Thursday murder club - Richard Osman ♣️
5. The Testaments - Margaret Atwood 
6. Conversations with friends - Sally Rooney 
7. The housekeeper and the professor - by Yōko Ogawa, Stephen Snyder (Translator)
8. The dice man - Luke Rhinehart ♣️
9. Introduction to statistical modelling of extreme values - Stuart Coles 
10. Stories of the law and how it is broken - The Secret Barrister
11. College Science Teaching - Terry McGlynn (2021-04-07)
12. In the dream house - Carmen Maria Machado ♣️
13. Radio Silence - Alice Oseman 
14. Your House is on Fire, Your Children All Gone - Stefan Kiesbye
15. Nick and Charlie - Alice Oseman 
16. Solaris - Stanisław Lem ♣️
17. Show your work - Austin Kleon 
18. Circe - Madeline Miller (2021-06-19)
19. Convenience Store Woman - Sayaka Murata
20. On being different - Merle Miller
21. Eating Animals - Jonathan Saffran Foer
22. Piranesi - Susan Clarke 
23. Happy git with R - Jenny Bryan
24. The inheritance of loss - Kiran Desai ♣️
25. Why I am no longer talking (to white people) about race - Reni Eddo-Lodge
26. Reputation - Lex Croucher ♣️ (2021-08-24)
27. The Ethical Algorithm - Michael Kearns and Aaron Roth (2021-09-02)
28. Everything I never told you - Celeste Ng
29. Invisible Women - Caroline Criado Perez 
30. Digital Minimalism - Cal Newport
31. The Best of Me - David Sedaris
32. Wicked - Gregory Maguire


## 2019-2020
1. What I talk about when I talk about running - Haruki Murakami 
2. Guys knit - Sockmatician 
3. Brit(ish) - Afua Hirsch 
4. Semicolon - Cecilia Watson 
5. The conscious closet - Elizabeth L. Cline 
6. A little book of language - David Crystal 
7. Hardboiled wonderland and the end of the world - Haruki Murakami 
8. The Topeka school - Ben Lerner
9. Normal people - Sally Rooney
10. Show your work - Austin Kleon 
11. 1Q84 (Book 1) - Haruki Murakami
12. 1Q84 (Book 2) - Haruki Murakami
13. 1Q84 (Book 3) - Haruki Murakami
14. The body - Bill Bryson 
15. You too can have a body like mine - Alexandra Kleeman
16. I'm thinking of ending things - Iain Reed 
17. Supper club - Lara Williams
18. Girl, woman, other - Bernadine Evaristo ♣️
19. Lolita - Vladimir Nabokov ♣️
20. Severance - Ling Ma 
21. The school of life - Alain de Botton
22. ...


## 2018-2019
1. Have you eaten Grandma? - Giles Brandreth 
2. An edited life - Anna Newton 
3. Weight expectations - Dave Chawner
4. Spirits of the season - Tanya Kirk
5. Killing Comendatore - Haruki Murakami 
6. Happy ever after - Paul Dolan
7. Dress your family in corduroy and denim - David Sedaris
8. Hear the wind sing - Haruki Murakami
9. Pinball 1973 - Haruki Murakami 
10. Call me by your name - Andre Aciman 
11. The visual display of quantitative information - Edward R. Tufte 
12. The elephant vanishes - Haruki Murakami 
13. A brave new world - Aldous Huxley 
14. The missing piece - Shell Silverstein 
15. The joy of work - Bruce Daisley 
16. Joined up writing -Roger McGough 
17. The idiot - Elif Batuman 
18. The slow professor - Maggie Berg & Barbara Seeber 
19. The history boys - Alan Bennett 
20. The handmaid's tale - Margaret Atwood 
21. Classical mechanics - Leonard Susskind & George Hrabovsky 
22. Indistractable - Nir Eyal 
23. Are you experienced - William Sutcliffe 
24. Calypso - David Sedaris 
25. No one is too small to make a difference - Greta Thunberg

## 2017-2018
1. Bridget Jones' diary - Helen Fielding 
 2. The mathematics of Christmas - Hannah Fry 
 3. Call me by your name - Andre Aciman 
 4. Talking to my daughter about the economy - Yanis Varoufakis 
 5. Irresistable - Adam Alter 
 6. Sympathy - Olivia Sudjic 
 7. Moranifesto - Caitlin Moran 
 8. iGen - Jean Twenge 
 9. Hagseed - Margaret Atwood 
 10. Norse Mythology - Neil Gaiman 
 11. Upper North Tynedale - Beryl Charlton 
 12. Talk like TED - Carmine Gallo 
 13. The boy on the Bridge - Mike Carey 
 14. Men without women - Haruki Murakami 
 15. South of the border, West of the sun - Haruki Murakami 
 16. Queer city - Peter Ackroyd 
 17. Less - Andrew Sean Greer 
 18. Why the Dutch are different - Ben Coates 
 19. Rest - Alex Soojung-Kim Pang 
 20. Wicked - Gregory Maguire 
 21. Women and power - Mary Beard 
 22. Girls will be girls - Emer O'Toole 
 23. The boy in the striped pajamas - John Boyne 
 24. :heavy_multiplication_x: 


## 2016-2017
 1. The throwback - Tom Sharpe 
 2. Seven brief lessons on physics - Carlo Rovelli 
 3. The Circle - Dave Eggers 
 4. Five on brexit island - Bruno Vincent 
 5. You too can have a body like mine - Alexandra Kleeman 
 6. The wish - Bill Griffin 
 7. Happy - Derren Brown 
 8. A little gay history - R.B. Parkinson 
 9. Nina is not OK - Shappi Khorsandi 
 10. The life-changing magic of tidying - Marie Kondo 
 11. The vegetarian - Han Kang 
 12. Respectable - Lyndsey Hanley
 13. The great indoors - Ben Highmore 
 14. Solitude - Michael Harris 
 15. Icecream for breakfast - Laure Jane Williams 
 16. American Gods - Neil Gaiman 
 17. Bossy pants - Tina Fey 
 18. Quiet - Susan Cain 
 19. Harry Potter and the philospoher's stone - J.K. Rowling 
 20. Harry Potter and the chamber of secrets - J.K. Rowling
 21. Gerald's game - Stephen King
 22. The handmaid's tale - Margaret Atwood
 23. Not working - Lisa Owens 
 24. Kafka on the Shore - Haruki Murakami
