# Research Project Supervision

I have had the good fortune to supervise some exceptional early career researchers in their postgraduate and undergraduate research projects. Below is a list of the students I have supervised along with their project titles.

## PhD 

- __Conor Murphy__ (Oct 2021 - Present) Assessment of hazard and risk due to induced seismicity for underground CO2 Storage and oil and gas production assets. 


## MSc and MSci

- __Wanchen Yue__ - Evolution of statistical earthquake models to account for measurement errors and dependence.
- __Ash Bellett__ - Topics in complex data generating processes (title TBC).
- __Christian Liman__ - Topics in complex data generating processes (title TBC).
- __Li Vern Teo__ - Topics in complex data generating processes (title TBC).
- __Minjian Wu__ - Topics in complex data generating processes (title TBC).
- __Paula Cordero Encinar__ - Representing ignorance about extreme earthquake magnitudes.
- __Lucy He__ - Including measurement error in earthquake modelling.
- __Shantianfang Gao__ - Inhomogeneous Poisson point process estimation using spline methods.
- __Diana Xu__ - An extreme value mixture model for natural gas prices.
- __Hugo Barnett__ - Hypothesis testing with the self-inhibiting Hawkes process.
- __Nan Zhou__ - Self-driving vehicles road safety analysis by application of extreme value theory.
- __Xuan Hou__ - An extreme value analysis of rainfall in London.
- __Conor Murphy__ - Assessment of hazard and risk due to induced seismicity for underground CO2 Storage and oil and gas production assets.


## Undergraduate

- __Natalie Young__ - Point pattern analysis in statistical ecology.
- __Peter Greenstreet__ - Self-exciting point process models.
