# Talks

## Upcoming


No upcoming talks currently scheduled. 

Have a speaking opportunity that you think I'd be great for? [Let me know about it](](https://twitter.com/messages/compose?recipient_id={4708109019}))!



## Archive 

### 2023

#### RSS Local Group Meeting - University of Bath
:::{.callout-warning appearance="minimal" collapse=true}
## Shaking Things Up: Statistical Modelling of Earthquakes

Thursday 16 November 2023 (15:15 - 16:15) [Register](https://rss.org.uk/training-events/events/events-2023/local-groups/rss-avon-local-group-agm-and-talk-on-earthquake-mo/#eventoverview)


__Slides__: 

<a href="../assets/talks/2023-RSS-shaking-things-up.html" class="btn btn-outline-primary m-1" target="_blank">HTML <span class="bi bi-filetype-html"></span></a>
<!-- -->
<a href="../assets/talks/2023-RSS-shaking-things-up.pdf" class="btn btn-outline-primary m-1">PDF <span class="bi bi-file-pdf"></span></a>
<!-- -->
<a href="https://github.com/zakvarty/talks/tree/main/2023-RSS-shaking-things-up" class="btn btn-outline-primary m-1" target="_blank">Source <span class="bi bi bi-file-earmark-code"></span></a> 


__Abstract:__

Earthquakes are among the most unpredictable of natural disasters and can have a profound impact on both human society and the built environment. Understanding the processes underlying seismic events is crucial to being able to map and mitigate against the hazards that they present.

In this talk, we'll start by introducing some basic seismology principles and the data that can be collected through monitoring networks. We'll then investigate some of the statistical models commonly used to describe earthquake behaviour, from simple point processes to more complex branching process representations and extreme value statistics. Along the way, we'll discuss the challenges of applying these models to real earthquake data and highlight the growing role of machine learning in earthquake research.

We'll explore recent approaches that address the limitations and uncertainties in earthquake modelling, so that by the end of this talk you'll have both a solid understanding of the fundamental models in statistical seismology and an insight into their potential future developments.
:::

#### Royal Statistical Society Conference 2023

:::{.callout-warning appearance="minimal" collapse=true}
## Getting Your Work to Work in Academia (and Beyond) 

__Slides__: 
<!-- -->
<a href="../assets/talks/2023-RSS-getting-your-work-to-work.html" class="btn btn-outline-primary m-1" target="_blank">HTML <span class="bi bi-filetype-html"></span></a>
<!-- -->
<a href="../assets/talks/2023-RSS-getting-your-work-to-work.pdf" class="btn btn-outline-primary m-1">PDF <span class="bi bi-file-pdf"></span></a>
<!-- -->
<a href="https://github.com/zakvarty/talks/tree/main/2023-RSS-getting-your-work-to-work" class="btn btn-outline-primary m-1" target="_blank">Source <span class="bi bi bi-file-earmark-code"></span></a> 



__Abstract:__

You can't solve a hard problem all in one go. One example of this is the ongoing replication crisis faced by the academic world, where published results can't be verified by independent repetition of the original study. So, what do we do when we can't solve a hard problem straight away? We find a sub-problem that we can solve and use that as a steppingstone towards our final goal. In the case of the replication crisis, we can narrow our scope to reproducibility: given the same experimental or observational data can the original results be recovered?

This talk will focus on the ways that reproducibility interacts with three aspects of academic (and non-academic) work: research, teaching, and the training our future colleagues. I'll share my experiences of moving toward a more reproducible way of working and argue that the individual and collective benefits of working reproducibility more than justify the extra effort this requires.


:::


#### Royal Statistical Society Conference 2023 (Pre-conference Workshop)

:::{.callout-warning appearance="minimal" collapse=true}
## Go Figure!

__Slides:__ 
<!-- -->
<a href="../assets/talks/2023-RSS-go-figure.html" class="btn btn-outline-primary m-1" target="_blank">HTML <span class="bi bi-filetype-html"></span></a>
<!-- -->
<a href="../assets/talks/2023-RSS-go-figure.pdf" class="btn btn-outline-primary m-1">PDF <span class="bi bi-file-pdf"></span></a>
<!-- -->
<a href="https://github.com/zakvarty/talks/tree/main/2023-RSS-go-figure" class="btn btn-outline-primary m-1" target="_blank">Source <span class="bi bi bi-file-earmark-code"></span></a> 



__Abstract:__

As the saying goes, a picture is worth a thousand words. If that’s true then the importance of high quality figures should not be underestimated. In this session, we’ll explore how you can effectively support and explain your research using visualisations.

We’ll begin with some design principles to help your figures to clearly convey your intended meaning. We’ll then develop strategies to adapt your figures for different audiences and introduce tools to make them accessible to a broader audience. To put your new-found knowledge to the test, we’ll conclude the session with a game of broken picture telephone (including prizes for the winners!).
:::


#### Imperial Inspirational Lecture Series: Ethics in Mathematics + Panel Discussion

:::{.callout-warning appearance="minimal" collapse=true}
## Ethical Considerations in Data Science

__Abstract:__

Data ethics is a rapidly developing area within data science, covering a wide range of topics and every stage in the life cycle of a data science project. It aims to answer questions such as:

- What data are we reasonably allowed to gather, for how long can we keep it and how do we store it securely?
- For personal information, which attributes should we obscuring or avoiding entirely in our modelling process? 
- How can we evaluate the models that we do fit to ensure that they protect the privacy of the individuals within the training data? How can we quantify the fairness of the decisions and predictions that those models make, and can we test whether are fair? 
- Once models are in production and impacting people's lives, how do we ensure those models remain relevant and how do we prevent our models from perpetuating historical biases? 

We will take loan applications as an example to explore some of the challenges you might face when you have to answer these questions about your own work.
:::


#### IMA Idea Exchange - Early Career Mathematicians and Statisticians Teaching in Higher Education

:::{.callout-warning appearance="minimal" collapse=true}
## Peer-graded assessments as part of an online degree

<a href="../assets/talks/2023_IMA_peer-graded-assessments.pdf" class="btn btn-outline-primary m-1">Slides <span class="bi bi-file-pdf"></span></a> 
<!-- -->
<a href="https://youtu.be/gxFc3qnmsQY?t=8240" target="_blank" rel="noopener noreferrer" class="btn btn-outline-primary m-1">Video <span class="bi bi-youtube"></span></a> 

__Abstract:__

Who actually does the required reading before class? Honestly, very few people. Solving this problem can be relatively straightforward if we appropriately reward students for doing that reading. The best reward will differ between students: for one it might be course credit, for another detailed written feedback or for another it might be feeling well prepare to participate in class discussions. 

In this short talk, I will discuss how introducing peer-marked reading summaries improved the teaching and learning experiences in an online course on ethical data science. I'll give some context about the course and describe how we introduced the peer-marked assignments as well as the impact this has had on teaching and learning (both positive and negative).
:::

### 2022 

#### Royal Statistical Society Conference 2022

:::{.callout-warning title="Abstract" appearance="minimal" collapse=true}
## Incorporating Ethics into the Data Science Curriculum 

<a href="../assets/talks/2022_RSS_slides_zak_varty.pdf" class="btn btn-outline-primary m-1">Slides <span class="bi bi-file-pdf"></span></a>

__Abstract:__

Data-driven decision making is now pervasive and impacts us all. Your data is used by others to make decisions about who you are, how you will behave, and what options should be made available to you. Predictive models are used to decide anything from the promotion that is offered to you by a retailer through to whether your loan application is granted by a bank.  

The ways in which these predictive models can fail mathematically form a core part of the training for an aspiring statistician or data scientist. In contrast, the potential for ethical failures in these same models is rarely covered in-depth during as part of this initial training. As a result, these modes of failure are often not considered until those predictive models have been put into production and are actively causing harm. We argue that to prevent this harm, the ethical impacts of using data to make decisions must be made core to the curriculum of both statistics and data science.  

This talk will describe how this may be done in a way that is appealing to an audience with a strong mathematical focus and that does not require the authoring of extended essays or moral treaties. The discussion is structured around the development of a post-graduate course in the Ethics of Data Science, but the core ideas are salient to all statistics training. Throughout, we give actionable ways in which these topics may be integrated into statistical training at all levels. 
:::

----

Older talks will be added here as time allows. 
